---
name: ${IMAGE_NAME}
services:
  container:
    image: >-
      ${REGISTRY_BASE}/${REGISTRY_PROJECT}/${IMAGE_NAME}:rb-theron-gazebo-${DOCKER_ROS_DISTRO}-${GITHUB_REF_NAME}
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
      network: host
      pull: true
      no_cache: true
      args:
        # Base image to contruct current image
        base_image: ${REGISTRY_BASE}/robotnik/ros
        image_base_version: ${IMAGE_BASE_VERSION}
        ros_distro: ${DOCKER_ROS_DISTRO}
        version: ${GITHUB_REF_NAME}
        builder_type: ${BUILDER_TYPE}
        ros_mirror: ${ROS_MIRROR}
