---
name: rb-theron-sim
services:
  core:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    build:
      pull: true
      no_cache: true
      context: ../..
      dockerfile: container/builder/Dockerfile
      args:
        # Base image to contruct current image
        image_base_version: 0.5.0
        ros_distro: noetic
        base_image: registry.robotnik.ws/robotnik/ros
        # With no local copy or the repos
        # base: use the git from vcs
        # local: use the ones from the local repo
        builder_type: local
        version: devel
