---
name: rb-theron-sim
services:
  core:
    image: >-
      robotnik/robotnik-simulations:rb-theron-gazebo-${ROS_DISTRO}-${VERSION}
    build:
      pull: true
      no_cache: true
      context: ../..
      dockerfile: container/builder/Dockerfile
      args:
        base_image: ${REGISTRY_BASE}robotnik/ros
        image_base_version: ${IMAGE_BASE_VERSION}
        ros_distro: ${ROS_DISTRO}
        version: ${VERSION}
        builder_type: ${BUILDER_TYPE}
