---
name: rb-theron-sim
services:
  core:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    build:
      context: ../..
      dockerfile: container/builder/Dockerfile
      args:
        # Base image to contruct current image
        # image_base_version: 0.4.0
        image_base_version: a07f857-20231115
        ros_distro: noetic
        # With no local copy or the repos
        # base: use the git from vcs
        # local: use the ones from the local repo
        builder_type: local
