---
name: rb-theron-sim
services:
  core:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    build:
      context: ../..
      dockerfile: docker/builder/Dockerfile
      args:
        # Base image to contruct current image
        # image_base_version: 0.4.0
        image_base_version: c1038f3-20231113
        ros_distro: noetic
