---
name: rb-theron-sim
services:
  base:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    network_mode: "host"
    privileged: true
    group_add:
      - dialout
      - plugdev
      - video
    environment:
      ROS_MASTER_URI: "http://localhost:11311"
      GAZEBO_MASTER_URI: "http://localhost:11345"
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: 1
      LIBGL_ALWAYS_INDIRECT: 0

      STARTUP_TYPE: generic
      GEN_COMMAND: sleep infinity
      SIGNAL_DESTROY: SIGTERM

      # ROBOT QUANTITY
      ROBOT_QTY: 1

      # ROBOT 1
      X_INIT_POSE: "0.0"
      Y_INIT_POSE: "0.0"
      Z_INIT_POSE: "0.0"
      INIT_YAW: "0.0"

      # ROBOT 2
      R2_X_INIT_POSE: "2.0"
      R2_Y_INIT_POSE: "1.0"
      R2_Z_INIT_POSE: "0.00"
      R2_INIT_YAW: "0.0"

      # ROBOT 3
      R3_X_INIT_POSE: "-2.0"
      R3_Y_INIT_POSE: "-1.0"
      R3_Z_INIT_POSE: "0.00"
      R3_INIT_YAW: "0.0"

      # ROBOT 4
      R4_X_INIT_POSE: "-2.0"
      R4_Y_INIT_POSE: "1.0"
      R4_Z_INIT_POSE: "0.00"
      R4_INIT_YAW: "0.0"

      # ROBOT 5
      R5_X_INIT_POSE: "2.0"
      R5_Y_INIT_POSE: "-1.0"
      R5_Z_INIT_POSE: "0.00"
      R5_INIT_YAW: "0.0"

      # LAUNCH COMPONENTS
      LAUNCH_GMAPPING: "false"
      LAUNCH_AMCL: "true"
      LAUNCH_MAPSERVER: "true"
      LAUNCH_MOVE_BASE: "true"
      LAUNCH_PAD: "true"
      LAUNCH_RVIZ: "true"
      LAUNCH_LASER_MERGER: "true"
      LAUNCH_WEB_BACKEND: "false"
      LAUNCH_WEB_THROTTLE: "false"
      LAUNCH_POSE_PUBLISHER: "false"

      # GAZEBO PARAMETERS
      USE_GPU: "false"
      VERBOSE: "true"
      GUI: "true"
      DEBUG: "false"

      # ROBOTS PARAMETERS
      ROSBRIDGE_PORT: "9090"
      ROBOT_WEB_VIDEO_SERVER_PORT: "8092"
      ROBOT_WEB_VIDEO_QUALITY: "50"
      ROBOT_WEB_VIDEO_TRANSPORT: "compresed"
      ROBOT_HMI_2D_SENSOR_1: "merged_laser/scan"
      POSE_PUBLISHER_FREQUENCY: 10
      POSE_PUBLISHER_BASE_FRAME_SUFFIX: "base_footprint"
      POSE_PUBLISHER_TOPIC_REPUB: "robot_pose"

    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: /dev
        target: /dev
    devices:
      - "/dev/dri"
