---
name: rb-theron-sim

volumes:
  web:
  config:
  data:

services:
  gazebo-server:
    image: >-
      robotnik/robotnik-simulations:rb-theron-gazebo-${DOCKER_ROS_DISTRO}-${VERSION}
    env_file:
      - ../environment/web/gazebo-params.env
      - ../environment/web/launch-components.env
      - ../environment/web/robot-params.env
      - ../environment/web/robot-qty.env
      - ../environment/robots-pose.env
    environment:
      ROS_MASTER_URI: "http://localhost:11311"
      GAZEBO_MASTER_URI: "http://localhost:11345"
      FAKE_SCREEN: "true"
      # # Uncomment for Debuging
      # SIGNAL_DESTROY: SIGTERM
      # STARTUP_TYPE: generic
      # GENERIC_CMD: sleep infinity

  web-files:
    image: robotnik/novnc:${NOVNC_VERSION}
    volumes:
      - type: volume
        source: web
        target: /data/web
      - type: volume
        source: config
        target: /data/config

  fileserver:
    image: robotnik/filebrowser:${FILEBROWSER_VERSION}
    volumes:
      - type: volume
        source: data
        target: /srv
    ports:
      - protocol: tcp
        target: 80
        published: ${FILEBROWSER_PORT}
        mode: host

  rviz:
    image: >-
      robotnik/robotnik-simulations:rb-theron-gazebo-${DOCKER_ROS_DISTRO}-${VERSION}
    env_file:
      - ../environment/web/robot-qty.env
      - ../environment/web/uri-params.env
    environment:
      VNC_RFBPORT: 5900
      ROS_BU_LAUNCH: rviz_only.launch
      GUI_COMMAND: 'roslaunch $${ROS_BU_PKG} $${ROS_BU_LAUNCH}'
      STARTUP_TYPE: graphical
      GUI_ZENITY_TEXT: "Launch rviz?"
      HEALTHCHECK_NODES: "/rviz"
    volumes:
      - type: volume
        source: data
        target: /home/robot/data

  physics-change:
    image: >-
      robotnik/robotnik-simulations:rb-theron-gazebo-${DOCKER_ROS_DISTRO}-${VERSION}
    restart: on-failure
    env_file:
      - ../environment/gazebo-physics.env
      - ../environment/web/uri-params.env
    environment:
      CHECK_NODES: true
      NODES_TO_CHECK: "/gazebo"
      STARTUP_TYPE: "generic"
      SIGNAL_DESTROY: SIGTERM
      GEN_COMMAND: |
        source ~/.bashrc && {
        rosservice call /gazebo/set_physics_properties "time_step: $${TIME_STEP}
        max_update_rate: $${MAX_UPDATE_RATE}
        gravity:
          x: 0.0
          y: 0.0
          z: -9.8
        ode_config: {
            auto_disable_bodies: false,
            sor_pgs_precon_iters: 0,
            sor_pgs_iters: 40,
            sor_pgs_w: 1.0,
            sor_pgs_rms_error_tol: 0.0,
            contact_surface_layer: 0.0,
            contact_max_correcting_vel: 100.0,
            cfm: 0.0,
            erp: 0.2,
            max_contacts: 20
        }" || { echo notworking; exit 1;} ;} &&
        rosservice call /gazebo/unpause_physics "{}" || exit 1

  rviz-websocket:
    image: robotnik/websockify:${WEBSOCKIFY_VERSION}
    restart: always
    env_file:
      - ../environment/web/websocket-params.env
    environment:
      VNC_HOST: rviz
    ports:
      - protocol: tcp
        target: 6080
        published: ${WS_RVIZ_PORT}

  rviz-webserver:
    image: nginx:${NGINX_VERSION}
    restart: always
    env_file:
      - ../environment/web/nginx-params.env
    environment:
      PHP_SERVER: rviz-phpserver
    ports:
      - target: 80
        published: ${NGINX_RVIZ_PORT}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
      - type: volume
        source: config
        target: /etc/nginx/templates/

  rviz-phpserver:
    image: php:${PHP_VERSION}
    restart: always
    environment:
      WEBSOCKITY_PORT: ${WS_RVIZ_PORT}
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web

  gz-client:
    image: >-
      robotnik/robotnik-simulations:rb-theron-gazebo-${DOCKER_ROS_DISTRO}-${VERSION}
    env_file:
      - ../environment/web/robot-qty.env
      - ../environment/web/uri-params.env
    environment:
      VNC_RFBPORT: 5900
      GUI_COMMAND: 'gzclient'
      STARTUP_TYPE: graphical
      SIGNAL_DESTROY: SIGTERM
      GUI_ZENITY_TEXT: "Launch Gazebo?"
    volumes:
      - type: volume
        source: data
        target: /home/robot/data

  gz-client-websocket:
    image: robotnik/websockify:${WEBSOCKIFY_VERSION}
    env_file:
      - ../environment/web/websocket-params.env
    environment:
      VNC_HOST: gz-client
    ports:
      - protocol: tcp
        target: 6080
        published: ${WS_GZ_PORT}


  gz-client-webserver:
    image: nginx:${NGINX_VERSION}
    env_file:
      - ../environment/web/nginx-params.env
    environment:
      PHP_SERVER: gz-client-phpserver
    ports:
      - target: 80
        published: ${NGINX_GZ_PORT}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
      - type: volume
        source: config
        target: /etc/nginx/templates/

  gz-client-phpserver:
    image: php:${PHP_VERSION}
    environment:
      WEBSOCKITY_PORT: ${WS_GZ_PORT}
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
