---
x-public-reg: &public_reg ../environment/compose/registry-docker-hub.env
x-private-reg: &private_reg ../environment/compose/registry-robotnik.env
x-version: &version ../environment/compose/version.env
x-web-ports: &web_ports ../environment/compose/web-ports.env
x-web-version: &web_version ../environment/compose/web-versions.env

include:
  - path:
      - ../compose/simulation-backend.yaml
      - ../compose/web-common.yaml
    project_directory: .
    env_file:
      - *version
      - *web_ports
      - *web_version
      - *public_reg
      # - *private_reg
