---
name: rb-theron-sim

volumes:
  web:
  config:
  data:

services:
  gazebo-server:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    env_file:
      - ../environment/web/gazebo-params.env
      - ../environment/web/launch-components.env
      - ../environment/web/robot-params.env
      - ../environment/web/robot-qty.env
      - ../environment/robots-pose.env
    environment:
      ROS_MASTER_URI: "http://localhost:11311"
      GAZEBO_MASTER_URI: "http://localhost:11345"
      FAKE_SCREEN: "true"
      # # Uncomment for Debuging
      # SIGNAL_DESTROY: SIGTERM
      # STARTUP_TYPE: generic
      # GENERIC_CMD: sleep infinity

  web-files:
    image: robotnik/novnc:web-1.3.0-2-rc02
    volumes:
      - type: volume
        source: web
        target: /data/web
      - type: volume
        source: config
        target: /data/config

  fileserver:
    image: robotnik/filebrowser:2.24.2-1
    volumes:
      - type: volume
        source: data
        target: /srv
    ports:
      - target: 80
        published: 7081
        protocol: tcp
        mode: host

  rviz:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    env_file:
      - ../environment/web/robot-qty.env
      - ../environment/web/uri-params.env
    environment:
      VNC_RFBPORT: 5900
      ROS_BU_LAUNCH: rviz_only.launch
      GUI_COMMAND: 'roslaunch $${ROS_BU_PKG} $${ROS_BU_LAUNCH}'
      STARTUP_TYPE: graphical
      GUI_ZENITY_TEXT: "Launch rviz?"
      HEALTHCHECK_NODES: "/rviz"
    volumes:
      - type: volume
        source: data
        target: /home/robot/data

  rviz-websocket:
    image: robotnik/websockify:backend-0.11.0-1
    restart: always
    env_file:
      - ../environment/web/websocket-params.env
    environment:
      VNC_HOST: rviz
    ports:
      - protocol: tcp
        target: 6080
        published: 7083

  rviz-webserver:
    image: nginx:1.25.1-alpine3.17
    restart: always
    env_file:
      - ../environment/web/nginx-params.env
    environment:
      PHP_SERVER: rviz-phpserver
    ports:
      - target: 80
        published: 7080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
      - type: volume
        source: config
        target: /etc/nginx/templates/

  rviz-phpserver:
    image: php:8.0.30-fpm-alpine3.16
    restart: always
    environment:
      WEBSOCKITY_PORT: 7083
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web

  gz-client:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    env_file:
      - ../environment/web/robot-qty.env
      - ../environment/web/uri-params.env
    environment:
      VNC_RFBPORT: 5900
      GUI_COMMAND: 'gzclient'
      STARTUP_TYPE: graphical
      SIGNAL_DESTROY: SIGTERM
      GUI_ZENITY_TEXT: "Launch Gazebo?"
    volumes:
      - type: volume
        source: data
        target: /home/robot/data

  gz-client-websocket:
    image: robotnik/websockify:backend-0.11.0-1
    env_file:
      - ../environment/web/websocket-params.env
    environment:
      VNC_HOST: gz-client
    ports:
      - protocol: tcp
        target: 6080
        published: 7085

  gz-client-webserver:
    image: nginx:1.25.1-alpine3.17
    env_file:
      - ../environment/web/nginx-params.env
    environment:
      PHP_SERVER: gz-client-phpserver
    ports:
      - target: 80
        published: 7082
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
      - type: volume
        source: config
        target: /etc/nginx/templates/

  gz-client-phpserver:
    image: php:8.0.30-fpm-alpine3.16
    environment:
      WEBSOCKITY_PORT: 7085
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
