---
name: rb-theron-sim

volumes:
  web:
  config:
  data:

services:
  gazebo-server:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    env_file:
      - ../environment/web/gazebo-params.env
      - ../environment/web/launch-components.env
      - ../environment/web/robot-params.env
      - ../environment/web/robot-qty.env
      - ../environment/robots-pose.env
    environment:
      ROS_MASTER_URI: "http://localhost:11311"
      GAZEBO_MASTER_URI: "http://localhost:11345"

  rviz:
    image: robotnik/robotnik-simulations:rb-theron-gazebo-noetic-devel
    environment:
      ROS_MASTER_URI: "http://gazebo-server:11311"
      GAZEBO_MASTER_URI: "http://gazebo-server:11345"
      VNC_RFBPORT: 5900
      RVIZ_CONFIG_FILE:
        /opt/ros/noetic/share/rb_theron_gazebo/rviz/rb_theron.rviz
      GUI_COMMAND: 'rviz -d $${RVIZ_CONFIG_FILE}'
      STARTUP_TYPE: graphical
      GUI_ZENITY_TEXT: "Launch rviz?"
      HEALTHCHECK_NODES: "/rviz"
    volumes:
      - type: volume
        source: data
        target: /home/robot/data

  websocket:
    image: robotnik/websockify:backend-0.11.0-1
    restart: always
    environment:
      USE_ENV_CONFIG: "true"
      VERBOSE: "true"
      VNC_HOST: rviz
      VNC_PORT: 5900
      WS_PORT: 5080
    ports:
      - protocol: tcp
        target: 5080
        published: 7083

  web-files:
    image: robotnik/novnc:web-1.3.0-2-rc02
    volumes:
      - type: volume
        source: web
        target: /data/web
      - type: volume
        source: config
        target: /data/config

  webserver:
    image: nginx:1.25.1-alpine3.17
    restart: always
    environment:
      NGINX_PORT: 80
      NGINX_SERVER: localhost
      WEBSITE_PATH: "/var/www/html/web"
      PHP_SERVER: phpserver
      PHP_PORT: 9000
    ports:
      - target: 80
        published: 7080
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web
      - type: volume
        source: config
        target: /etc/nginx/templates/

  phpserver:
    image: php:8.0.30-fpm-alpine3.16
    restart: always
    environment:
      WEBSOCKITY_PORT: 7083
    volumes:
      - type: volume
        source: web
        target: /var/www/html/web

  fileserver:
    image: robotnik/filebrowser:2.24.2-1
    volumes:
      - type: volume
        source: data
        target: /srv
    ports:
      - target: 80
        published: 7081
        protocol: tcp
        mode: host
